# Generated by Django 4.2.28 on 2026-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Brakes', 'Brakes'), ('Tires', 'Tires'), ('Engine', 'Engine'), ('Climate', 'Climate'), ('Electrical', 'Electrical'), ('Other', 'Other')], default='Maintenance', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['category', 'name'],
            },
        ),
    ]
