# Generated by Django 4.2.28 on 2026-02-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
    ]
