# Generated by Django 4.2.28 on 2026-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(default='AutoGarage', max_length=255)),
                ('email', models.EmailField(default='support@autogarage.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 000-0000', max_length=50)),
                ('address', models.TextField(default='123 Garage Street, New York, NY 10001')),
                ('email_notifications', models.BooleanField(default=True)),
                ('overdue_reminders', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
            ],
        ),
    ]
